name: Release

on:
  workflow_dispatch:
    inputs:
      tag_overwrite:
        description: 'Overwrite existing tag'
        required: false
        default: false
        type: boolean
  workflow_call:

# This is required to be able to update tags and create releases
permissions:
  contents: write

jobs:
  check-dist:
    name: Check dist/
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v7
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm ci

      - name: Build dist/ Directory
        id: build
        run: npm run bundle

      # This will fail the workflow if the `dist/` directory is different than
      # expected.
      - name: Compare Directories
        id: diff
        run: |
          if [ ! -d dist/ ]; then
            echo "Expected dist/ directory does not exist.  See status below:"
            ls -la ./
            exit 1
          fi
          if [ "$(git diff --ignore-space-at-eol --text dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff --ignore-space-at-eol --text dist/
            exit 1
          fi

  release:
    name: Release Version
    needs: check-dist
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with fetch-tags set to true
      - name: Checkout
        id: checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      # Get the version and update the tags to use in the release
      - name: Tag Commit
        id: tag-commit
        uses: issue-ops/semver@v3
        with:
          manifest-path: package.json
          overwrite: ${{ github.event.inputs.tag_overwrite }}

      # Use the version output from the previous step for the release
      # Prepends a 'v' to the beginning (e.g. 'v1.2.3')
      - name: Create Release
        id: create-release
        uses: issue-ops/releaser@v3
        with:
          tag: v${{ steps.tag-commit.outputs.version }}
